# Generated by Django 4.1.6 on 2023-03-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tromapp', '0002_campus_cursus_faculty_job_person_friends_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(),
        ),
    ]
