# Generated by Django 4.1.6 on 2023-03-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tromapp', '0004_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(),
        ),
    ]
