# Generated by Django 4.1.6 on 2023-05-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tromapp', '0006_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='invitation',
            field=models.ManyToManyField(to='tromapp.person'),
        ),
    ]
