# Generated by Django 4.1.6 on 2023-05-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tromapp', '0008_remove_person_invitation_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
    ]
