# Generated by Django 4.1.6 on 2023-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tromapp', '0010_message_publication_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
